services:

  postgres-1:
    image: postgres:14.0
    container_name: dpfsd-postgres-1
    environment:
      POSTGRES_DB: dpfsd-1
      POSTGRES_USER: utenteDev
      POSTGRES_PASSWORD: passwordDev
    ports:
      - "54321:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data
    network_mode: bridge
    restart: always